stages:
  preprocess:
    cmd: python src/data_pipeline.py
    deps:
      - data/iris_full.csv
      - src/data_pipeline.py
    params:
      - TEST_SIZE
      - RANDOM_STATE
    outs:
      - data/processed

  train:
    cmd: python src/model_pipeline.py
    deps:
      - data/processed
      - src/model_pipeline.py
    params:
      - training
      - RANDOM_STATE
    outs:
      - models