stages:
  preprocess:
    cmd: python train/data_preprocessing.py
    deps:
      - data/iris_full.csv
      - train/data_preprocessing.py
    params:
      - TEST_SIZE
      - RANDOM_STATE
    outs:
      - data/processed_data.pkl

  train:
    cmd: python train/model_training.py
    deps:
      - data/processed_data.pkl
      - train/model_training.py
    params:
      - training
      - RANDOM_STATE
    outs:
      - models