stages:
  load_data:
    cmd: python src/data_pipeline.py load
    deps:
    - src/data_pipeline.py
    outs:
    - data/iris.csv

  split_data:
    cmd: python src/data_pipeline.py split
    deps:
    - data/iris.csv
    - src/data_pipeline.py
    outs:
    - data/train.csv
    - data/test.csv

