TEST_SIZE: 0.2
RANDOM_STATE: 42
training:
  mlflow_experiment_name: "Iris-Classifier-DVC"
  models:
    LogisticRegression:
      C: 1.0
      solver: "lbfgs"
    RandomForest:
      n_estimators: 100
      max_depth: 10